# fly.toml app configuration file generated for todoapp-spring-brook-5982-little-grass-565-silent-shape-3149 on 2024-01-20T18:20:46+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "todoapp-spring-brook-5982-little-grass-565-silent-shape-3149"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
